version: "3.1"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: quitto
    ports:
      - 5432:5432

  quitto-backend:
    build:
      context: "./api"
      dockerfile: "Dockerfile.local"
    restart: on-failure
    volumes:
      - ./api:/home/node/
    env_file: ./api/.env
    ports:
      - 3000:3000
